services:
  database:
    image: mysql
    container_name: travel-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  phpMyAdmin: 
    image: phpmyadmin
    container_name: travel-phpMyAdmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - 8080:80